services:
  db:
    container_name: architechture_postgres
    image: postgres
    restart: always
    volumes:
      - .:/code
    env_file:
      - .env
  pgadmin:
    restart: always
    container_name: architechture_pgadmin
    image: 'dpage/pgadmin4'
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - 5050:80
    depends_on:
      - db
  web:
    container_name: architechture_web
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
  redis:
    image: redis
    container_name: architechture_redis
    ports:
      - '6379:6379'
    restart: always
  celery:
    restart: always
    build: .
    env_file:
      - .env
    container_name: architechture_celery
    command: celery -A architechture worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
      - web
